<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // City::factory(50)->create();

        City::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 1,
                'country_id' => 1,
                'name' => '臺北市',
                'name_en' => 'Taipei City',
                'slug' => 'TPE',
                'latitude' => 25.0330,
                'longitude' => 121.5654,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'country_id' => 1,
                'name' => '新北市',
                'name_en' => 'New Taipei City',
                'slug' => 'NWT',
                'latitude' => 25.0120,
                'longitude' => 121.4657,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'country_id' => 1,
                'name' => '桃園市',
                'name_en' => 'Taoyuan City',
                'slug' => 'TYC',
                'latitude' => 24.9936,
                'longitude' => 121.3010,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'country_id' => 1,
                'name' => '臺中市',
                'name_en' => 'Taichung City',
                'slug' => 'TXG',
                'latitude' => 24.1477,
                'longitude' => 120.6736,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'country_id' => 1,
                'name' => '臺南市',
                'name_en' => 'Tainan City',
                'slug' => 'TNN',
                'latitude' => 22.9997,
                'longitude' => 120.2270,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'country_id' => 1,
                'name' => '高雄市',
                'name_en' => 'Kaohsiung City',
                'slug' => 'KHH',
                'latitude' => 22.6273,
                'longitude' => 120.3014,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'country_id' => 1,
                'name' => '基隆市',
                'name_en' => 'Keelung City',
                'slug' => 'KEE',
                'latitude' => 25.1276,
                'longitude' => 121.7392,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'country_id' => 1,
                'name' => '新竹市',
                'name_en' => 'Hsinchu City',
                'slug' => 'HSZ',
                'latitude' => 24.8138,
                'longitude' => 120.9675,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'country_id' => 1,
                'name' => '嘉義市',
                'name_en' => 'Chiayi City',
                'slug' => 'CYI',
                'latitude' => 23.4801,
                'longitude' => 120.4491,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'country_id' => 1,
                'name' => '新竹縣',
                'name_en' => 'Hsinchu County',
                'slug' => 'HSQ',
                'latitude' => 24.8387,
                'longitude' => 121.0177,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'country_id' => 1,
                'name' => '苗栗縣',
                'name_en' => 'Miaoli County',
                'slug' => 'MIA',
                'latitude' => 24.5602,
                'longitude' => 120.8214,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'country_id' => 1,
                'name' => '彰化縣',
                'name_en' => 'Changhua County',
                'slug' => 'CHA',
                'latitude' => 24.0800,
                'longitude' => 120.5388,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'country_id' => 1,
                'name' => '南投縣',
                'name_en' => 'Nantou County',
                'slug' => 'NAN',
                'latitude' => 23.9609,
                'longitude' => 120.9719,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'country_id' => 1,
                'name' => '雲林縣',
                'name_en' => 'Yunlin County',
                'slug' => 'YUN',
                'latitude' => 23.7092,
                'longitude' => 120.4313,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'country_id' => 1,
                'name' => '嘉義縣',
                'name_en' => 'Chiayi County',
                'slug' => 'CYQ',
                'latitude' => 23.4518,
                'longitude' => 120.2550,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'country_id' => 1,
                'name' => '屏東縣',
                'name_en' => 'Pingtung County',
                'slug' => 'PIF',
                'latitude' => 22.5519,
                'longitude' => 120.5488,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'country_id' => 1,
                'name' => '宜蘭縣',
                'name_en' => 'Yilan County',
                'slug' => 'ILA',
                'latitude' => 24.7021,
                'longitude' => 121.7378,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'country_id' => 1,
                'name' => '花蓮縣',
                'name_en' => 'Hualien County',
                'slug' => 'HUA',
                'latitude' => 23.9872,
                'longitude' => 121.6015,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'country_id' => 1,
                'name' => '臺東縣',
                'name_en' => 'Taitung County',
                'slug' => 'TTT',
                'latitude' => 22.7583,
                'longitude' => 121.1444,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'country_id' => 1,
                'name' => '澎湖縣',
                'name_en' => 'Penghu County',
                'slug' => 'PEN',
                'latitude' => 23.5712,
                'longitude' => 119.5793,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'country_id' => 1,
                'name' => '金門縣',
                'name_en' => 'Kinmen County',
                'slug' => 'KIN',
                'latitude' => 24.4321,
                'longitude' => 118.3171,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'country_id' => 1,
                'name' => '連江縣',
                'name_en' => 'Lienchiang County',
                'slug' => 'LIE',
                'latitude' => 26.1602,
                'longitude' => 119.9517,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
