<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\Fortune;

class Fortune06Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fortune::factory(150)->create();

        // 觀音二八籤
        Fortune::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 601,
                'fortune_category_id' => 6,
                'fortune_no' => 1,
                'title' => '第一籤',
                'content' => '福如東海壽南山，<br/>君爾何須嘆苦難，<br/>榮華富貴天注定，<br/>貴人太白守身邊。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■太白吉星',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 602,
                'fortune_category_id' => 6,
                'fortune_no' => 2,
                'title' => '第二籤',
                'content' => '寶鏡團圓似月明，<br/>琴瑟和諧暢我情，<br/>婚姻商賈皆如意，<br/>登科一舉狀元名。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 603,
                'fortune_category_id' => 6,
                'fortune_no' => 3,
                'title' => '第三籤',
                'content' => '啞人得夢口難言，<br/>瞎眼穿針更不然，<br/>九曲明珠穿不過，<br/>孔子在陳必絕糧。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 604,
                'fortune_category_id' => 6,
                'fortune_no' => 4,
                'title' => '第四籤',
                'content' => '白虎出山欲害人，<br/>誤入羅網難脫身，<br/>害人終歸反害己，<br/>蟲飛入火自損身。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■白虎關煞',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 605,
                'fortune_category_id' => 6,
                'fortune_no' => 5,
                'title' => '第五籤',
                'content' => '梅花映雪正芳菲，<br/>江海漁翁下釣磯，<br/>夜靜水寒魚不餌，<br/>滿船空載月明歸。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■景好■待機■運滯■無收',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 606,
                'fortune_category_id' => 6,
                'fortune_no' => 6,
                'title' => '第六籤',
                'content' => '富貴總由天注定，<br/>五穀豐登勝上年，<br/>共享太平歌舜日，<br/>含哺鼓腹樂堯天。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■含哺即吹奏,鼓腹同鼓舞',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 607,
                'fortune_category_id' => 6,
                'fortune_no' => 7,
                'title' => '第七籤',
                'content' => '鯉魚志氣本英雄，<br/>屈在池中運未通，<br/>一旦飛來頭角現，<br/>風雲際會變成龍。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 608,
                'fortune_category_id' => 6,
                'fortune_no' => 8,
                'title' => '第八籤',
                'content' => '皇天降下紫微星，<br/>除奸滅惡得安寧，<br/>二十八宿扶聖主，<br/>漢國江山再重興。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■紫微星主文■宿指星座',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 609,
                'fortune_category_id' => 6,
                'fortune_no' => 9,
                'title' => '第九籤',
                'content' => '鬼門關上遇無常，<br/>鐵船過海浪頭風，<br/>口愿冤愆如羅網，<br/>爾欲嘉時得禍殃。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■愿未還■爾同你',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 610,
                'fortune_category_id' => 6,
                'fortune_no' => 10,
                'title' => '第十籤',
                'content' => '三藏取經往西天，<br/>路途險要得齊天，<br/>雲橫秦嶺家何在，<br/>雪擁藍關馬不前。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■齊天指孫悟空喻貴人■指韓愈被貶旅途之苦',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 611,
                'fortune_category_id' => 6,
                'fortune_no' => 11,
                'title' => '第十一籤',
                'content' => '八仙過海赴蟠桃，<br/>龍王拖下藍彩和，<br/>因奪玉板刀兵戰，<br/>彌陀慈心來講和。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■各顯神通,藍彩和八仙之一■喻有爭端,以和為貴',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 612,
                'fortune_category_id' => 6,
                'fortune_no' => 12,
                'title' => '第十二籤',
                'content' => '夫婦有意兩相謀，<br/>綢繆未合反成愁，<br/>萬事逢春皆大吉，<br/>姻緣註定不須求。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■春有作秋',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 613,
                'fortune_category_id' => 6,
                'fortune_no' => 13,
                'title' => '第十三籤',
                'content' => '伏羲八卦最精靈，<br/>六十甲子排五星，<br/>暗室虧心天地見，<br/>舉頭三所有神明。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■五星金木水火土同五行',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 614,
                'fortune_category_id' => 6,
                'fortune_no' => 14,
                'title' => '第十四籤',
                'content' => '張弓射月箭虛空，<br/>朽木難雕柱費工，<br/>本心勝念千年佛，<br/>作惡免燒萬座香。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■方向死■材料死■立心死■行為死,拒改實死',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 615,
                'fortune_category_id' => 6,
                'fortune_no' => 15,
                'title' => '第十五籤',
                'content' => '昔日螳螂往捕蟬，<br/>豈知黃雀在身邊，<br/>莫信此人直中直，<br/>須防其心仁不仁。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 616,
                'fortune_category_id' => 6,
                'fortune_no' => 16,
                'title' => '第十六籤',
                'content' => '牛郎織女本天仙，<br/>阻隔銀河路杳然，<br/>百年富貴風中灼，<br/>一旦榮華夢裏仙。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 617,
                'fortune_category_id' => 6,
                'fortune_no' => 17,
                'title' => '第十七籤',
                'content' => '雷霆霹靂震當空，<br/>天罡差我察吉凶，<br/>積善之家必有慶，<br/>積惡之家定遭殃。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■天罡北斗星君■喻抽簽者須即去惡從善,雷神示警',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 618,
                'fortune_category_id' => 6,
                'fortune_no' => 18,
                'title' => '第十八籤',
                'content' => '風和浪靜可行舟，<br/>高歌鼓腹樂優游，<br/>四皓八仙齊暢飲，<br/>十八學士登瀛洲。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■鼓腹同鼓舞■皓指白首借喻漢初四隱士■唐太宗文學館賢才,瀛洲指仙境',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 619,
                'fortune_category_id' => 6,
                'fortune_no' => 19,
                'title' => '第十九籤',
                'content' => '日上東方吹散雲，<br/>光明清彩照乾坤，<br/>二十四氣真清吉，<br/>一年四季太平春。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■乾坤天地■氣節陰曆',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 620,
                'fortune_category_id' => 6,
                'fortune_no' => 20,
                'title' => '第二十籤',
                'content' => '一盞明燈對面休，<br/>主人有福再添油，<br/>任他險處不見險，<br/>若再災禍可無憂。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■休即熄,危象■須繼續行善積福如此才可脫險',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 621,
                'fortune_category_id' => 6,
                'fortune_no' => 21,
                'title' => '第二一籤',
                'content' => '太公釣渭八十秋，<br/>除商滅紂再興周，<br/>民安國泰太平世，<br/>江山萬里任君遊。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■靜待時機■大器晚成',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 622,
                'fortune_category_id' => 6,
                'fortune_no' => 22,
                'title' => '第二二籤',
                'content' => '若要求財未得財，<br/>只恐鬼賊相侵害，<br/>關門閉戶家中坐，<br/>災禍皆從天上來。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■運極滯,自招天譴,即改惡',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 623,
                'fortune_category_id' => 6,
                'fortune_no' => 23,
                'title' => '第二三籤',
                'content' => '魚在小澗上長灘，<br/>淺處難遊深處安，<br/>心虛不守誤君事，<br/>夷齊餓死首陽山。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■夷齊商朝人,轉周朝恥食周粟,喻頑固',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 624,
                'fortune_category_id' => 6,
                'fortune_no' => 24,
                'title' => '第二四籤',
                'content' => '囚人出獄上酒樓，<br/>暢飲幾杯解心愁，<br/>有事當忍一時氣，<br/>非干己事莫當頭。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 625,
                'fortune_category_id' => 6,
                'fortune_no' => 25,
                'title' => '第二五籤',
                'content' => '三人異姓同一心，<br/>桃園結義意情深，<br/>崑山美玉皆是寶，<br/>我身是鐵變成金。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 626,
                'fortune_category_id' => 6,
                'fortune_no' => 26,
                'title' => '第二六籤',
                'content' => '釋迦化出妙色身，<br/>老君抱送玉麒麟，<br/>真宗求嗣生貴子，<br/>梁紇禱丘產聖人。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■佛祖可見,喻吉時吉境也■麒麟祥瑞獸■宋真宗得仁宗,喻求貴得貴■叔梁紇生孔子,丘指尼丘,山名,喻求仁得仁■叔梁紇,注意不是孔梁紇',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 627,
                'fortune_category_id' => 6,
                'fortune_no' => 27,
                'title' => '第二七籤',
                'content' => '落葉根在莫憂老，<br/>枯木逢春在發花，<br/>雖是中間多進退，<br/>錢財到底屬我家。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 628,
                'fortune_category_id' => 6,
                'fortune_no' => 28,
                'title' => '第二八籤',
                'content' => '信心者得福，<br/>不信者得禍，<br/>百事上吉，<br/>謝油三斗。合朝君臣離別凶，<br/>沖天卓地決有凶，<br/>項王勢敗烏江刎，<br/>屈願柱死汨羅江。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => '■斗本作斤■卓即插撞鑿',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
