<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\Fortune;

class Fortune08Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fortune::factory(150)->create();

        // 金錢卦三二籤
        Fortune::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 801,
                'fortune_category_id' => 8,
                'fortune_no' => 1,
                'title' => '第壹號',
                'content' => '彩鳳呈祥瑞，<br/>麒麟降帝都，<br/>禍除迎福至，<br/>喜氣自然生。',
                'summary' => '禍消福至<br/>求管得位<br/>求財大利<br/>婚姻成就<br/>出行大吉<br/>占病得安<br/>作事大吉<br/>考試得意',
                'level' => '上上',
                'code' => '○○○○○',
                'image' => '/images/fortunes/08/01.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 802,
                'fortune_category_id' => 8,
                'fortune_no' => 2,
                'title' => '第貳號',
                'content' => '從革宜更變，<br/>時來合動遷，<br/>龍門魚耀出，<br/>凡骨作神仙。',
                'summary' => '行事得利<br/>作事可成<br/>占訟和吉<br/>求官得位<br/>走失見近<br/>婚姻成吉<br/>運途漸吉<br/>作事如意',
                'level' => '上平',
                'code' => '○●●●●',
                'image' => '/images/fortunes/08/02.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 803,
                'fortune_category_id' => 8,
                'fortune_no' => 3,
                'title' => '第叁號',
                'content' => '動作因風便，<br/>求謀可托人，<br/>若逢戊己土，<br/>事事得遂心。',
                'summary' => '出行吉利<br/>謀事成就<br/>占孕生男<br/>家宅大吉<br/>運途漸轉<br/>占病不妨<br/>作事如意<br/>月令小吉',
                'level' => '中平',
                'code' => '●○●●●',
                'image' => '/images/fortunes/08/03.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 804,
                'fortune_category_id' => 8,
                'fortune_no' => 4,
                'title' => '第肆號',
                'content' => '船放江湖內，<br/>灘邊穫寶多，<br/>更宜將大用，<br/>災散福來居。',
                'summary' => '人口平安<br/>作事小心<br/>求財六分<br/>六甲生男<br/>交易成吉<br/>占訟和吉<br/>行人得信<br/>運途好轉',
                'level' => '小平',
                'code' => '●●○●●',
                'image' => '/images/fortunes/08/04.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 805,
                'fortune_category_id' => 8,
                'fortune_no' => 5,
                'title' => '第伍號',
                'content' => '此籤按南方，<br/>災厄不可當，<br/>官司多不利，<br/>目下有災殃。',
                'summary' => '求謀有阻<br/>出行平平<br/>求財落空<br/>占訟不和<br/>婚姻平常<br/>尋人不見<br/>家室小康<br/>運途不好',
                'level' => '下下',
                'code' => '●●●○●',
                'image' => '/images/fortunes/08/05.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 806,
                'fortune_category_id' => 8,
                'fortune_no' => 6,
                'title' => '第陸號',
                'content' => '且安君子分，<br/>勿用小人言，<br/>凡事皆當謹，<br/>作福保安然。',
                'summary' => '謀事不成<br/>家運小康<br/>作事不好<br/>占訟不好<br/>考試不利<br/>出行小心<br/>行人成至<br/>六甲生女',
                'level' => '中平',
                'code' => '●●●●○',
                'image' => '/images/fortunes/08/06.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 807,
                'fortune_category_id' => 8,
                'fortune_no' => 7,
                'title' => '第柒號',
                'content' => '國治人安泰，<br/>家財漸漸興，<br/>有財求望吉，<br/>有福亦平安。',
                'summary' => '求官得位<br/>作事成就<br/>開市大吉<br/>六甲生男<br/>求財十分<br/>家宅大吉<br/>占訟有理<br/>運途如意',
                'level' => '上上',
                'code' => '○○●●●',
                'image' => '/images/fortunes/08/07.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 808,
                'fortune_category_id' => 8,
                'fortune_no' => 8,
                'title' => '第捌號',
                'content' => '好德承天佑，<br/>門招喜氣新，<br/>有人相助力，<br/>獲福盡歡欣。',
                'summary' => '求官得位<br/>求財十分<br/>六甲生男<br/>考試上一<br/>占病得安<br/>婚姻成就<br/>作事可成<br/>運途如意',
                'level' => '上吉',
                'code' => '○●○●●',
                'image' => '/images/fortunes/08/08.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 809,
                'fortune_category_id' => 8,
                'fortune_no' => 9,
                'title' => '第玖號',
                'content' => '目下如冬樹，<br/>枯木未開花，<br/>看看春色動，<br/>漸漸發萌芽。',
                'summary' => '求官遠吉<br/>占病無訪<br/>求財三分<br/>六甲生女<br/>婚姻暫談<br/>尋人得見<br/>考試得中<br/>運途大吉',
                'level' => '中吉',
                'code' => '○●●●○',
                'image' => '/images/fortunes/08/09.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 810,
                'fortune_category_id' => 8,
                'fortune_no' => 10,
                'title' => '第拾號',
                'content' => '時融逢和氣，<br/>衰殘物再興，<br/>更逢微細雨，<br/>春色又還生。',
                'summary' => '謀事可成<br/>運途小吉<br/>作事小心<br/>求財八分<br/>交易和合<br/>六甲生男<br/>口舌無妨<br/>婚姻成就',
                'level' => '中平',
                'code' => '○●●○●',
                'image' => '/images/fortunes/08/10.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 811,
                'fortune_category_id' => 8,
                'fortune_no' => 11,
                'title' => '第拾壹號',
                'content' => '災散福門開，<br/>無邊喜氣來，<br/>目下相逢處，<br/>須當得橫財。',
                'summary' => '求官得位<br/>求財九分<br/>六甲生男<br/>婚姻成就<br/>家宅安康<br/>運途如意<br/>生意得利<br/>貴人扶持',
                'level' => '大吉',
                'code' => '●○○●○',
                'image' => '/images/fortunes/08/11.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 812,
                'fortune_category_id' => 8,
                'fortune_no' => 12,
                'title' => '第拾貳號',
                'content' => '進取逢通達，<br/>寒儒衣錦歸，<br/>有人占取卦，<br/>凡事任意為。',
                'summary' => '求官得位<br/>占訟和吉<br/>口舌無妨<br/>作事可成<br/>求財八分<br/>出行大吉<br/>婚姻可成<br/>運途大利',
                'level' => '上平',
                'code' => '●○●○●',
                'image' => '/images/fortunes/08/12.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 813,
                'fortune_category_id' => 8,
                'fortune_no' => 13,
                'title' => '第拾叁號',
                'content' => '井底觀明月，<br/>見影卻無形，<br/>錢財多散失，<br/>謹守得安寧。',
                'summary' => '謀事不成<br/>交易不利<br/>求財落空<br/>尋人不見<br/>六甲生女<br/>行人未至<br/>生意不利<br/>運途大兇',
                'level' => '下兇',
                'code' => '●○●●○',
                'image' => '/images/fortunes/08/13.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 814,
                'fortune_category_id' => 8,
                'fortune_no' => 14,
                'title' => '第拾肆號',
                'content' => '心思多不定，<br/>求謀未得成，<br/>忍耐方為福，<br/>守分免災星。',
                'summary' => '功名未遂<br/>出行不宜<br/>作事不成<br/>占病難癒<br/>六甲生女<br/>口舌臨身<br/>運途不好<br/>凡事小吉',
                'level' => '下中',
                'code' => '●●○○●',
                'image' => '/images/fortunes/08/14.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 815,
                'fortune_category_id' => 8,
                'fortune_no' => 15,
                'title' => '第拾伍號',
                'content' => '枯木逢霜雪，<br/>扁舟遇大風，<br/>驚心無可免，<br/>百事不行通。',
                'summary' => '求財不利<br/>尋人不見<br/>走失落空<br/>六甲生男<br/>婚姻不成<br/>占訟不和<br/>運途不利<br/>身體小康',
                'level' => '下兇',
                'code' => '●●○●○',
                'image' => '/images/fortunes/08/15.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 816,
                'fortune_category_id' => 8,
                'fortune_no' => 16,
                'title' => '第拾陸號',
                'content' => '日出臨東海，<br/>光輝天下明，<br/>動用和合吉，<br/>百事自然成。',
                'summary' => '求官得位<br/>求財九分<br/>作事可成<br/>官訟和理<br/>口舌消散<br/>光明上進<br/>運途如意<br/>婚姻成就',
                'level' => '平吉',
                'code' => '●●●○○',
                'image' => '/images/fortunes/08/16.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 817,
                'fortune_category_id' => 8,
                'fortune_no' => 17,
                'title' => '第拾柒七號',
                'content' => '眾惡皆消滅，<br/>端然福氣生，<br/>如人行暗夜，<br/>今已得天明。',
                'summary' => '謀事暫成<br/>作事平平<br/>求財六分<br/>婚姻平常<br/>身體小康<br/>六甲生女<br/>出行謀財<br/>事事遂心',
                'level' => '中吉',
                'code' => '○○○●●',
                'image' => '/images/fortunes/08/17.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 818,
                'fortune_category_id' => 8,
                'fortune_no' => 18,
                'title' => '第拾捌號',
                'content' => '服藥將身保，<br/>纏綿詞訟連，<br/>百凡宜守舊，<br/>作福自然安。',
                'summary' => '口舌無妨<br/>謀事可成<br/>凡事小心<br/>求財七分<br/>求官得位<br/>家運小康<br/>六甲生男<br/>占並無妨',
                'level' => '中平',
                'code' => '○○●○●',
                'image' => '/images/fortunes/08/18.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 819,
                'fortune_category_id' => 8,
                'fortune_no' => 19,
                'title' => '第拾玖號',
                'content' => '籤中多恍惚，<br/>錢財暗裡磨，<br/>恩深成怨去，<br/>人事不須知。',
                'summary' => '出行小心<br/>婚姻不成<br/>謀事不成<br/>貴人不佳<br/>凡事不好<br/>錢財落空<br/>人口不安<br/>家運不利',
                'level' => '下下',
                'code' => '○○●●○',
                'image' => '/images/fortunes/08/19.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 820,
                'fortune_category_id' => 8,
                'fortune_no' => 20,
                'title' => '第貳拾號',
                'content' => '根實枝葉茂，<br/>林多格式高，<br/>經榮多得利，<br/>蘭蕙似逢篙。',
                'summary' => '謀事成就<br/>求官得位<br/>出行大吉<br/>月令平常<br/>身體小康<br/>口舌消除<br/>作事可成<br/>家運如意',
                'level' => '上平',
                'code' => '○●○○●',
                'image' => '/images/fortunes/08/20.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 821,
                'fortune_category_id' => 8,
                'fortune_no' => 21,
                'title' => '第貳拾壹號',
                'content' => '求名居祿位，<br/>籠鳥得逃生，<br/>出入多財寶，<br/>更宜遠方行。',
                'summary' => '婚姻可成<br/>謀事成就<br/>求官得位<br/>占訟和吉<br/>求財大利<br/>口舌消散<br/>作事可成<br/>運途如意',
                'level' => '上吉',
                'code' => '○●○●○',
                'image' => '/images/fortunes/08/21.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 822,
                'fortune_category_id' => 8,
                'fortune_no' => 22,
                'title' => '第貳拾貳號',
                'content' => '明月清天上，<br/>今宵照綺筵，<br/>家家沾恩澤，<br/>萬里淨雲烟。',
                'summary' => '出行大吉<br/>求官得位<br/>口舌消散<br/>婚姻成就<br/>凡事如意<br/>事事遂心<br/>生意得利<br/>身體安康',
                'level' => '吉',
                'code' => '○●●○○',
                'image' => '/images/fortunes/08/22.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 823,
                'fortune_category_id' => 8,
                'fortune_no' => 23,
                'title' => '第貳拾叁號',
                'content' => '福祿得安康，<br/>榮華保吉昌，<br/>所得皆遂意，<br/>千里共蘭香。',
                'summary' => '婚姻可成<br/>先明上進<br/>求財十分<br/>交易大利<br/>作事成就<br/>生意得利<br/>六甲生男<br/>家運平安',
                'level' => '吉',
                'code' => '●○○○●',
                'image' => '/images/fortunes/08/23.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 824,
                'fortune_category_id' => 8,
                'fortune_no' => 24,
                'title' => '第貳拾肆號',
                'content' => '羸馬登程去，<br/>飢人走遠途，<br/>前人多阻厄，<br/>退後禍方無。',
                'summary' => '婚姻平平<br/>六甲生女<br/>求官不成<br/>謀事不成<br/>凡事小心<br/>走失不見<br/>求財落空<br/>運途不佳',
                'level' => '下',
                'code' => '●○○●●',
                'image' => '/images/fortunes/08/24.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 825,
                'fortune_category_id' => 8,
                'fortune_no' => 25,
                'title' => '第貳拾伍號',
                'content' => '三姓俱相伴，<br/>祥光得共生，<br/>更宜分造化，<br/>百福自然亨。',
                'summary' => '口舌消除<br/>求官得位<br/>六甲生男<br/>凡事平常<br/>求財六分<br/>作事小心<br/>出行大吉<br/>運途如意',
                'level' => '吉',
                'code' => '●○●○○',
                'image' => '/images/fortunes/08/25.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 826,
                'fortune_category_id' => 8,
                'fortune_no' => 26,
                'title' => '第貳拾陸號',
                'content' => '此籤占太和，<br/>求謀喜事多，<br/>遠人歸古里，<br/>身樂得歡歌。',
                'summary' => '口舌無妨<br/>出行大利<br/>謀事可成<br/>求官得位<br/>事事遂心<br/>作事成之<br/>求財七分<br/>家宅大吉',
                'level' => '吉',
                'code' => '●●○○○',
                'image' => '/images/fortunes/08/26.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 827,
                'fortune_category_id' => 8,
                'fortune_no' => 27,
                'title' => '第貳拾柒號',
                'content' => '霖雨滋稼穡，<br/>何愁不倍收，<br/>自然心得樂，<br/>安居總無憂。',
                'summary' => '婚姻可就<br/>占病無妨<br/>口舌消除<br/>出行大吉<br/>交易得意<br/>謀事成就<br/>求財七分<br/>運途大吉',
                'level' => '大中',
                'code' => '●○○○○',
                'image' => '/images/fortunes/08/27.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 828,
                'fortune_category_id' => 8,
                'fortune_no' => 28,
                'title' => '第貳拾捌號',
                'content' => '迢遞途中旅，<br/>雲橫日隨山，<br/>羈心無可托，<br/>前後總皆難。',
                'summary' => '求官得位<br/>凡事小心<br/>口舌臨身<br/>出行不利<br/>作事不成<br/>婚事不好<br/>六甲生女<br/>身體小康',
                'level' => '下',
                'code' => '○○○●○',
                'image' => '/images/fortunes/08/28.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 829,
                'fortune_category_id' => 8,
                'fortune_no' => 29,
                'title' => '第貳拾玖號',
                'content' => '畔中珠自見，<br/>石內玉争光，<br/>進財求望吉，<br/>有福不成殃。',
                'summary' => '占病無妨<br/>婚姻成就<br/>謀事成功<br/>口舌漸消<br/>貴人扶持<br/>出行大利<br/>光明上進<br/>家運小康',
                'level' => '吉',
                'code' => '○○●○○',
                'image' => '/images/fortunes/08/29.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 830,
                'fortune_category_id' => 8,
                'fortune_no' => 30,
                'title' => '第叁拾號',
                'content' => '天兵誅賊寇，<br/>旌旗得勝回，<br/>功勳為將帥，<br/>門第有光輝。',
                'summary' => '交友助成<br/>口舌消除<br/>婚姻可成<br/>求官得位<br/>出行大吉<br/>交易大利<br/>作事可成<br/>家運小康',
                'level' => '吉',
                'code' => '○○○○●',
                'image' => '/images/fortunes/08/30.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 831,
                'fortune_category_id' => 8,
                'fortune_no' => 31,
                'title' => '第叁拾壹號',
                'content' => '履簿登水池，<br/>危橋得渡時，<br/>重重憂險過，<br/>春色自芳菲。',
                'summary' => '占病不癒<br/>求官得位<br/>月令不佳<br/>出行小吉<br/>六甲生男<br/>尋人不見<br/>凡事小心<br/>家運小康',
                'level' => '平',
                'code' => '○●○○○',
                'image' => '/images/fortunes/08/31.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 832,
                'fortune_category_id' => 8,
                'fortune_no' => 32,
                'title' => '第叁拾貳號',
                'content' => '塵埋青鋼錢，<br/>美玉陷淤泥，<br/>何時重出世，<br/>再得光輝顯。',
                'summary' => '占訟不好<br/>婚姻不好<br/>謀事不成<br/>出行不利<br/>凡事小心<br/>口舌禍端<br/>財庫落空<br/>家運小康',
                'level' => '下',
                'code' => '●●●●●',
                'image' => '/images/fortunes/08/32.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
