<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\Fortune;

class Fortune01Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fortune::factory(150)->create();

        // 雷雨師一百籤
        Fortune::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 1,
                'fortune_category_id' => 1,
                'fortune_no' => 0,
                'title' => '籤王',
                'content' => '求得籤王百事良，<br/>萬事如意大吉昌，<br/>宜加力作行方便，<br/>可保福壽永安康。',
                'summary' => '絕大多數採用雷雨師一百籤的寺廟，是沒有此籤的。',
                'level' => null,
                'code' => null,
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'fortune_category_id' => 1,
                'fortune_no' => 1,
                'title' => '第一籤',
                'content' => '巍巍獨步向雲間，<br/>玉殿千官第一班，<br/>富貴榮華天付汝，<br/>福如東海壽如山。',
                'summary' => null,
                'level' => '大吉',
                'code' => '甲甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'fortune_category_id' => 1,
                'fortune_no' => 2,
                'title' => '第二籤',
                'content' => '盈虛消息總天時，<br/>自此君當百事宜，<br/>若問前程歸縮地，<br/>須憑方寸好修為。',
                'summary' => '(須憑兩字，另有改更須一說)',
                'level' => '上吉',
                'code' => '甲乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'fortune_category_id' => 1,
                'fortune_no' => 3,
                'title' => '第三籤',
                'content' => '衣食自然生處有，<br/>勸君不用苦勞心，<br/>但能孝悌存忠信，<br/>福祿來成禍不侵。',
                'summary' => null,
                'level' => '中吉',
                'code' => '甲丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'fortune_category_id' => 1,
                'fortune_no' => 4,
                'title' => '第四籤',
                'content' => '去年百事可相宜，<br/>若較今年時運衰，<br/>好把瓣香告神佛，<br/>莫教福謝悔無追。',
                'summary' => '(可字，另有改頗字一說)',
                'level' => '下下',
                'code' => '甲丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'fortune_category_id' => 1,
                'fortune_no' => 5,
                'title' => '第五籤',
                'content' => '子有三般不自由，<br/>門庭蕭索冷如秋，<br/>若逢牛鼠交承日，<br/>萬事回春不用憂。',
                'summary' => null,
                'level' => '中平',
                'code' => '甲戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'fortune_category_id' => 1,
                'fortune_no' => 6,
                'title' => '第六籤',
                'content' => '何勞鼓瑟更吹笙，<br/>寸步如登萬里程，<br/>彼此懷疑不相信，<br/>休將私意憶濃情。',
                'summary' => null,
                'level' => '下下',
                'code' => '甲己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'fortune_category_id' => 1,
                'fortune_no' => 7,
                'title' => '第七籤',
                'content' => '仙風道骨本天生，<br/>又遇仙宗為主盟，<br/>指日丹成謝巖谷，<br/>一朝引領向天行。',
                'summary' => null,
                'level' => '大吉',
                'code' => '甲庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'fortune_category_id' => 1,
                'fortune_no' => 8,
                'title' => '第八籤',
                'content' => '年來耕稼苦無收，<br/>今歲田疇定有秋，<br/>況遇太平無事日，<br/>士農工賈百無憂。',
                'summary' => null,
                'level' => '上上',
                'code' => '甲辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'fortune_category_id' => 1,
                'fortune_no' => 9,
                'title' => '第九籤',
                'content' => '望渠消息向長安，<br/>常把菱花仔細看，<br/>見說文書將入境，<br/>今朝喜色上眉端。',
                'summary' => null,
                'level' => '大吉',
                'code' => '甲壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'fortune_category_id' => 1,
                'fortune_no' => 10,
                'title' => '第十籤',
                'content' => '病患時時命蹇衰，<br/>何須打瓦共鑽龜，<br/>直教重見一陽後，<br/>始可求神仗佛持。',
                'summary' => '(後字，另有改復字一說)',
                'level' => '下下',
                'code' => '甲癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'fortune_category_id' => 1,
                'fortune_no' => 11,
                'title' => '第十一籤',
                'content' => '今年好事一番新，<br/>富貴榮華萃汝身，<br/>誰識機關難料處，<br/>到頭獨立轉傷神。',
                'summary' => '(識字，另有改道字一說)',
                'level' => '下下',
                'code' => '乙甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'fortune_category_id' => 1,
                'fortune_no' => 12,
                'title' => '第十二籤',
                'content' => '營為期望在春前，<br/>誰料秋來又不然，<br/>直遇清江貴公子，<br/>一生活計始安全。',
                'summary' => null,
                'level' => '中平',
                'code' => '乙乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'fortune_category_id' => 1,
                'fortune_no' => 13,
                'title' => '第十三籤',
                'content' => '君今庚甲未亨通，<br/>且向江頭作釣翁，<br/>玉兔重生應發跡，<br/>萬人頭上逞英雄。',
                'summary' => null,
                'level' => '中平',
                'code' => '乙丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'fortune_category_id' => 1,
                'fortune_no' => 14,
                'title' => '第十四籤',
                'content' => '一見佳人便喜歡，<br/>誰知去後有多般，<br/>人情冷暖君休訝，<br/>歷涉應知行路難。',
                'summary' => null,
                'level' => '下下',
                'code' => '乙丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'fortune_category_id' => 1,
                'fortune_no' => 15,
                'title' => '第十五籤',
                'content' => '兩家門戶各相當，<br/>不是姻緣莫較量，<br/>直待春風好消息，<br/>卻調琴瑟向蘭房。',
                'summary' => null,
                'level' => '中平',
                'code' => '乙戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'fortune_category_id' => 1,
                'fortune_no' => 16,
                'title' => '第十六籤',
                'content' => '官事悠悠難辨明，<br/>不如息了且歸耕，<br/>旁人煽惑君休信，<br/>此事當謀親弟兄。',
                'summary' => '(旁字，另有作傍字一說)',
                'level' => '下下',
                'code' => '乙己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'fortune_category_id' => 1,
                'fortune_no' => 17,
                'title' => '第十七籤',
                'content' => '田園價貫好商量，<br/>事到公庭彼此傷，<br/>縱使機關圖得勝，<br/>定為後世子孫殃。',
                'summary' => null,
                'level' => '下下',
                'code' => '乙庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'fortune_category_id' => 1,
                'fortune_no' => 18,
                'title' => '第十八籤',
                'content' => '知君指擬是空華，<br/>底事茫茫未有涯，<br/>牢把腳根踏實地，<br/>善為善應永無差。',
                'summary' => null,
                'level' => '中平',
                'code' => '乙辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'fortune_category_id' => 1,
                'fortune_no' => 19,
                'title' => '第十九籤',
                'content' => '嗟子從來未得時，<br/>今年星運頗相宜，<br/>營求動作都如意，<br/>和合婚姻誕貴兒。',
                'summary' => null,
                'level' => '上吉',
                'code' => '乙壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'fortune_category_id' => 1,
                'fortune_no' => 20,
                'title' => '第二十籤',
                'content' => '一生心事向誰論，<br/>十八灘頭說與君，<br/>世事盡從流水去，<br/>功名富貴等浮雲。',
                'summary' => null,
                'level' => '下下',
                'code' => '乙癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'fortune_category_id' => 1,
                'fortune_no' => 21,
                'title' => '第二十一籤',
                'content' => '與君夙昔結成冤，<br/>今日相逢那得緣，<br/>好把經文多諷誦，<br/>祈求戶內保嬋娟。',
                'summary' => '(那得二字，另有作顯惡一說)',
                'level' => '下下',
                'code' => '丙甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'fortune_category_id' => 1,
                'fortune_no' => 22,
                'title' => '第二二籤',
                'content' => '碧玉池中開白蓮，<br/>莊嚴色相自天然，<br/>生來骨格超凡俗，<br/>正是人間第一仙。',
                'summary' => null,
                'level' => '上吉',
                'code' => '丙乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'fortune_category_id' => 1,
                'fortune_no' => 23,
                'title' => '第二三籤',
                'content' => '花開花謝在春風，<br/>貴賤窮通百歲中，<br/>羨子榮華今已矣，<br/>到頭萬事總成空。',
                'summary' => null,
                'level' => '下下',
                'code' => '丙丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'fortune_category_id' => 1,
                'fortune_no' => 24,
                'title' => '第二四籤',
                'content' => '一春萬事苦憂煎，<br/>夏裏營求始帖然，<br/>更遇秋成冬至後，<br/>恰如騎鶴與腰纏。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '丙丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'fortune_category_id' => 1,
                'fortune_no' => 25,
                'title' => '第二五籤',
                'content' => '寅午戍年多阻滯，<br/>亥子丑月漸亨嘉，<br/>待逢玉兔金雞會，<br/>枯木逢春自放花。',
                'summary' => '(待字，另有改更字一說。)',
                'level' => '中平',
                'code' => '丙戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'fortune_category_id' => 1,
                'fortune_no' => 26,
                'title' => '第二六籤',
                'content' => '年來豐歉皆天數，<br/>祇是今年旱較多，<br/>與子定期三日內，<br/>田疇霑足雨滂沱。',
                'summary' => '(祇字，另有改作自字一說。)',
                'level' => '中吉',
                'code' => '丙己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'fortune_category_id' => 1,
                'fortune_no' => 27,
                'title' => '第二七籤',
                'content' => '世間萬物各有主，<br/>一粒一毫君莫取，<br/>英雄豪傑自天生，<br/>也須步步循規矩。',
                'summary' => null,
                'level' => '下下(中平)',
                'code' => '丙庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'fortune_category_id' => 1,
                'fortune_no' => 28,
                'title' => '第二八籤',
                'content' => '公侯將相本無種，<br/>好把勤勞契上天，<br/>人事盡從天理見，<br/>才高豈得困林泉。',
                'summary' => null,
                'level' => '上吉',
                'code' => '丙辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'fortune_category_id' => 1,
                'fortune_no' => 29,
                'title' => '第二九籤',
                'content' => '祖宗積德幾多年，<br/>源遠流長慶自然，<br/>若更操修無倦已，<br/>天須還汝舊青氈。',
                'summary' => null,
                'level' => '上上',
                'code' => '丙壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'fortune_category_id' => 1,
                'fortune_no' => 30,
                'title' => '第三十籤',
                'content' => '奉公謹守莫欺心，<br/>自有亨通吉利臨，<br/>目下營求且休矣，<br/>秋期與子定佳音。',
                'summary' => null,
                'level' => '中吉',
                'code' => '丙癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'fortune_category_id' => 1,
                'fortune_no' => 31,
                'title' => '第三一籤',
                'content' => '秋冬作事只尋常，<br/>春到門庭漸吉昌，<br/>千里信音符遠望，<br/>萱堂快樂未渠央。',
                'summary' => null,
                'level' => '中吉',
                'code' => '丁甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'fortune_category_id' => 1,
                'fortune_no' => 32,
                'title' => '第三二籤',
                'content' => '勞心汨汨竟何歸，<br/>疾病兼多是與非，<br/>事到頭來渾似夢，<br/>何如休要用心機。',
                'summary' => null,
                'level' => '下下',
                'code' => '丁乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'fortune_category_id' => 1,
                'fortune_no' => 33,
                'title' => '第三三籤',
                'content' => '不分南北與西東，<br/>眼底昏昏耳似聾，<br/>熟讀黃庭經一卷，<br/>不論貴賤與窮通。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '丁丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'fortune_category_id' => 1,
                'fortune_no' => 34,
                'title' => '第三四籤',
                'content' => '春夏纔過秋又冬，<br/>紛紛謀慮攪心胸，<br/>貴人垂手來相接，<br/>休把私心情意濃。',
                'summary' => '(接字，另有作援字一說)',
                'level' => '中平(中吉)',
                'code' => '丁丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'fortune_category_id' => 1,
                'fortune_no' => 35,
                'title' => '第三五籤',
                'content' => '一山如畫對清江，<br/>門裏團圓事事雙，<br/>誰料半途分折去，<br/>空幃無語對銀缸。',
                'summary' => null,
                'level' => '下下',
                'code' => '丁戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'fortune_category_id' => 1,
                'fortune_no' => 36,
                'title' => '第三六籤',
                'content' => '功名富貴自能為，<br/>偶著先鞭莫問伊，<br/>萬里鵬程君有分，<br/>吳山頂上好鑽龜。',
                'summary' => '(先字，另有作仙字一說，應以先字為準)',
                'level' => '上吉',
                'code' => '丁己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'fortune_category_id' => 1,
                'fortune_no' => 37,
                'title' => '第三七籤',
                'content' => '焚香來告復何辭，<br/>善惡平分汝自知，<br/>屏卻昧公心裏事，<br/>出門無礙是通時。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '丁庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'fortune_category_id' => 1,
                'fortune_no' => 38,
                'title' => '第三八籤',
                'content' => '蛩吟唧唧守孤幃，<br/>千里懸懸望信歸，<br/>等得榮華公子到，<br/>秋冬括括雨靡靡。',
                'summary' => null,
                'level' => '下下',
                'code' => '丁辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'fortune_category_id' => 1,
                'fortune_no' => 39,
                'title' => '第三九籤',
                'content' => '北山門外好安居，<br/>若問終時慎厥初，<br/>堪笑包藏許多事，<br/>鱗鴻雖便莫修書。',
                'summary' => '(外字，另有改作下字一說)',
                'level' => '下下(中下)',
                'code' => '丁壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'fortune_category_id' => 1,
                'fortune_no' => 40,
                'title' => '第四十籤',
                'content' => '新來換得好規模，<br/>何用隨他步與趨，<br/>只聽耳邊消息到，<br/>崎嶇歷盡見亨衢。',
                'summary' => null,
                'level' => '上吉',
                'code' => '丁癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'fortune_category_id' => 1,
                'fortune_no' => 41,
                'title' => '第四一籤',
                'content' => '自南自北自東西，<br/>欲到天涯誰作梯，<br/>遇鼠逢牛三弄笛，<br/>好將名姓榜頭題。',
                'summary' => null,
                'level' => '中吉(上吉)',
                'code' => '戊甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'fortune_category_id' => 1,
                'fortune_no' => 42,
                'title' => '第四二籤',
                'content' => '我曾許汝事和諧，<br/>誰料修為果自乖，<br/>但改新圖莫依舊，<br/>營謀應得稱心懷。',
                'summary' => '(果字，另有改作汝字一說)',
                'level' => '中吉',
                'code' => '戊乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'fortune_category_id' => 1,
                'fortune_no' => 43,
                'title' => '第四三籤',
                'content' => '一紙官書火急催，<br/>扁舟速下浪如雷，<br/>雖然目下多驚險，<br/>保汝平安去復回。',
                'summary' => null,
                'level' => '中吉',
                'code' => '戊丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'fortune_category_id' => 1,
                'fortune_no' => 44,
                'title' => '第四四籤',
                'content' => '汝是人中最吉人，<br/>誤為誤作損精神，<br/>堅牢一念酬香願，<br/>富貴榮華萃汝身。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '戊丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'fortune_category_id' => 1,
                'fortune_no' => 45,
                'title' => '第四五籤',
                'content' => '好將心地力耕耘，<br/>彼此山頭總是墳，<br/>陰地不如心地好，<br/>修為到底卻輸君。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '戊戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'fortune_category_id' => 1,
                'fortune_no' => 46,
                'title' => '第四六籤',
                'content' => '君是山中萬戶侯，<br/>信知騎馬勝騎牛，<br/>今朝馬上看山色，<br/>爭似騎牛得自由。',
                'summary' => null,
                'level' => '中平',
                'code' => '戊己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'fortune_category_id' => 1,
                'fortune_no' => 47,
                'title' => '第四七籤',
                'content' => '與君萬語復千言，<br/>祗欲平和雪爾冤，<br/>訟則終凶君記取，<br/>試於清夜把心捫。',
                'summary' => null,
                'level' => '下下(中平)',
                'code' => '戊庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'fortune_category_id' => 1,
                'fortune_no' => 48,
                'title' => '第四八籤',
                'content' => '登山涉水正天寒，<br/>兄弟姻親那得安，<br/>不遇虎頭人一喚，<br/>全家誰保汝重歡。',
                'summary' => '(不字，另有改作幸字一說)<br/>(誰字，另有改作遂字一說)',
                'level' => '中平(中吉)',
                'code' => '戊辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'fortune_category_id' => 1,
                'fortune_no' => 49,
                'title' => '第四九籤',
                'content' => '彼此居家只一山，<br/>如何似隔鬼門關，<br/>日月如梭人易老，<br/>許多勞碌不如閒。',
                'summary' => null,
                'level' => '下下',
                'code' => '戊壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'fortune_category_id' => 1,
                'fortune_no' => 50,
                'title' => '第五十籤',
                'content' => '人說今年勝去年，<br/>也須步步要週旋，<br/>一家和氣多生福，<br/>萋菲讒言莫聽偏。',
                'summary' => '(去字，另有改作舊字一說)<br/>(週字，另有改作周字一說)',
                'level' => '上平(上吉)',
                'code' => '戊癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'fortune_category_id' => 1,
                'fortune_no' => 51,
                'title' => '第五一籤',
                'content' => '君今百事且隨緣，<br/>水到渠成聽自然，<br/>莫嘆年來不如意，<br/>喜逢新運稱心田。',
                'summary' => null,
                'level' => '上吉',
                'code' => '己甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'fortune_category_id' => 1,
                'fortune_no' => 52,
                'title' => '第五二籤',
                'content' => '兀坐幽居歎寂寥，<br/>孤燈掩映度清宵，<br/>黃金忽報秋光好，<br/>活計扁舟渡北朝。',
                'summary' => '(黃字，另有改作萬字一說)',
                'level' => '上吉',
                'code' => '己乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'fortune_category_id' => 1,
                'fortune_no' => 53,
                'title' => '第五三籤',
                'content' => '艱難險阻路蹊蹺，<br/>南鳥孤飛依北巢，<br/>今日貴人曾識面，<br/>相逢卻在夏秋交。',
                'summary' => null,
                'level' => '下下',
                'code' => '己丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'fortune_category_id' => 1,
                'fortune_no' => 54,
                'title' => '第五四籤',
                'content' => '萬人叢裏逞英豪，<br/>便欲飛騰霄漢高，<br/>爭奈承流風未便，<br/>青燈黃卷且勤勞。',
                'summary' => null,
                'level' => '中平',
                'code' => '己丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'fortune_category_id' => 1,
                'fortune_no' => 55,
                'title' => '第五五籤',
                'content' => '勤耕力作莫蹉跎，<br/>衣食隨時安分過，<br/>縱使經商收倍利，<br/>不如逐歲廩米多。',
                'summary' => '(米字，另有改作禾字一說)',
                'level' => '中平',
                'code' => '己戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'fortune_category_id' => 1,
                'fortune_no' => 56,
                'title' => '第五六籤',
                'content' => '心頭理曲強詞遮，<br/>直欲欺官行路斜，<br/>一旦醜形臨月鏡，<br/>身投憲網莫咨嗟。',
                'summary' => null,
                'level' => '下下',
                'code' => '己己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'fortune_category_id' => 1,
                'fortune_no' => 57,
                'title' => '第五七籤',
                'content' => '事端百出慮雖長，<br/>莫聽人言自主張，<br/>一著仙機君記取，<br/>紛紛鬧裏更思量。',
                'summary' => null,
                'level' => '中平',
                'code' => '己庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'fortune_category_id' => 1,
                'fortune_no' => 58,
                'title' => '第五八籤',
                'content' => '蘇秦三寸足平生，<br/>富貴功名在此行，<br/>更好修為陰騭事，<br/>前程萬里自通亨。',
                'summary' => '(自字，另有改作有字一說)',
                'level' => '上吉',
                'code' => '己辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'fortune_category_id' => 1,
                'fortune_no' => 59,
                'title' => '第五九籤',
                'content' => '門衰戶冷苦伶仃，<br/>可嘆祈求不一靈，<br/>幸有祖宗陰騭在，<br/>香煙未斷續螟蛉。',
                'summary' => '(螟蛉指繼子)<br/>(可字，另有改作自字一說)',
                'level' => '中平',
                'code' => '己壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'fortune_category_id' => 1,
                'fortune_no' => 60,
                'title' => '第六十籤',
                'content' => '羨君兄弟好名聲，<br/>一意謙撝莫自矜，<br/>丹詔槐黃消息近，<br/>巍巍科甲兩同登。',
                'summary' => '(一意二字，另有改作只管一說)<br/>(消息二字，另有改作相逼一說)',
                'level' => '上上',
                'code' => '己癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'fortune_category_id' => 1,
                'fortune_no' => 61,
                'title' => '第六一籤',
                'content' => '嘯聚山林兇惡儔，<br/>善良無事苦煎憂，<br/>主人大笑出門去，<br/>不用干戈盜賊休。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '庚甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'fortune_category_id' => 1,
                'fortune_no' => 62,
                'title' => '第六二籤',
                'content' => '百千人面虎狼心，<br/>賴汝干戈用力深，<br/>得勝回時秋漸老，<br/>虎頭城裏喜相尋。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '庚乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'fortune_category_id' => 1,
                'fortune_no' => 63,
                'title' => '第六三籤',
                'content' => '曩時征北且圖南，<br/>筋力雖衰尚一堪，<br/>欲識生前君大數，<br/>前三三與後三三。',
                'summary' => '(曩同昔)<br/>(征字，另有改作敗字一說)',
                'level' => '中平(中吉)',
                'code' => '庚丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'fortune_category_id' => 1,
                'fortune_no' => 64,
                'title' => '第六四籤',
                'content' => '吉人相遇本和同，<br/>況有持謀天水翁，<br/>人力不勞公論協，<br/>事成功倍笑談中。',
                'summary' => null,
                'level' => '上上',
                'code' => '庚丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'fortune_category_id' => 1,
                'fortune_no' => 65,
                'title' => '第六五籤',
                'content' => '朔風凜凜正窮冬，<br/>漸覺門庭喜氣濃，<br/>更入新春人事後，<br/>衷言方得信先容。',
                'summary' => '(漸覺二字，另有改作多羨一說)',
                'level' => '上上',
                'code' => '庚戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'fortune_category_id' => 1,
                'fortune_no' => 66,
                'title' => '第六六籤',
                'content' => '耕耘只可在鄉邦，<br/>何用求謀向外方，<br/>只見今年新運好，<br/>門闌喜氣事雙雙。',
                'summary' => '(只見二字，另有改作見說一說)',
                'level' => '上上',
                'code' => '庚己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'fortune_category_id' => 1,
                'fortune_no' => 67,
                'title' => '第六七籤',
                'content' => '纔發君心天已知，<br/>何須問我決狐疑，<br/>願子改圖從孝悌，<br/>不愁家室不相宜。',
                'summary' => null,
                'level' => '中平',
                'code' => '庚庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'fortune_category_id' => 1,
                'fortune_no' => 68,
                'title' => '第六八籤',
                'content' => '南販珍珠北販鹽，<br/>年來幾倍貨財添，<br/>勸君止此求田舍，<br/>心欲多時何日厭。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '庚辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'fortune_category_id' => 1,
                'fortune_no' => 69,
                'title' => '第六九籤',
                'content' => '捨舟遵路總相宜，<br/>慎勿嬉遊逐貴兒，<br/>一夜樽前兄與弟，<br/>明朝仇敵又相隨。',
                'summary' => '(樽指酒杯)',
                'level' => '下下(中平)',
                'code' => '庚壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'fortune_category_id' => 1,
                'fortune_no' => 70,
                'title' => '第七十籤',
                'content' => '雷雨風雲各有司，<br/>至誠禱告莫生疑，<br/>與君定約為霖日，<br/>正是蘊隆中伏時。',
                'summary' => '(中伏指夏季大暑後第二旬庚日)',
                'level' => '中平(中吉)',
                'code' => '庚癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'fortune_category_id' => 1,
                'fortune_no' => 71,
                'title' => '第七一籤',
                'content' => '喜鵲簷前報好音，<br/>知君千里欲歸心，<br/>繡幃重結鴛鴦帶，<br/>葉落霜凋暮色侵。',
                'summary' => '(鵲字，另有改作雀字一說)<br/>(凋暮，另有改作飛寒一說)',
                'level' => '中平(中吉)',
                'code' => '辛甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'fortune_category_id' => 1,
                'fortune_no' => 72,
                'title' => '第七二籤',
                'content' => '河渠傍路有高低，<br/>可歎長途日已西，<br/>縱有榮華好時節，<br/>直須猴犬換金雞。',
                'summary' => null,
                'level' => '下下(中平)',
                'code' => '辛乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'fortune_category_id' => 1,
                'fortune_no' => 73,
                'title' => '第七三籤',
                'content' => '憶昔蘭房分半釵，<br/>而今忽把信音乖，<br/>痴心指望成連理，<br/>到底誰知事不諧。',
                'summary' => '(昔字，另有改作惜字一說)',
                'level' => '下下',
                'code' => '辛丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'fortune_category_id' => 1,
                'fortune_no' => 74,
                'title' => '第七四籤',
                'content' => '崔巍崔魏復崔巍，<br/>履險如夷去復來，<br/>身似菩提心似鏡，<br/>長安一道放春回。',
                'summary' => '(崔巍指高峻崎嶇)',
                'level' => '上吉',
                'code' => '辛丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'fortune_category_id' => 1,
                'fortune_no' => 75,
                'title' => '第七五籤',
                'content' => '生前結得好緣姻，<br/>一笑相逢情自親，<br/>相當人物無高下，<br/>得意休論富與貧。',
                'summary' => null,
                'level' => '中吉',
                'code' => '辛戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'fortune_category_id' => 1,
                'fortune_no' => 76,
                'title' => '第七六籤',
                'content' => '三千法律八千文，<br/>此事何如說與君，<br/>善惡兩途君自作，<br/>一生禍福此中分。',
                'summary' => null,
                'level' => '中平',
                'code' => '辛己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'fortune_category_id' => 1,
                'fortune_no' => 77,
                'title' => '第七七籤',
                'content' => '木有根荄水有源，<br/>君當自此究其原，<br/>莫隨道路人閒話，<br/>訟則終凶是至言。',
                'summary' => '(則字，另有改作到字一說)<br/>(荄音同該字，是草根之意，常被誤繕為亥字)',
                'level' => '下下(中下)',
                'code' => '辛庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'fortune_category_id' => 1,
                'fortune_no' => 78,
                'title' => '第七八籤',
                'content' => '家道豐腴自飽溫，<br/>也須肚裏立乾坤，<br/>財多害己君當省，<br/>福有胚胎禍有門。',
                'summary' => '(豐字，另有改作豊字一說)',
                'level' => '下下',
                'code' => '辛辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'fortune_category_id' => 1,
                'fortune_no' => 79,
                'title' => '第七九籤',
                'content' => '乾亥來龍仔細看，<br/>坎居午向自當安，<br/>若移丑艮陰陽逆，<br/>門戶凋零家道難。',
                'summary' => '(當字，另有改作相字一說)',
                'level' => '中平',
                'code' => '辛壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'fortune_category_id' => 1,
                'fortune_no' => 80,
                'title' => '第八十籤',
                'content' => '一朝無事忽遭官，<br/>也是門衰墳未安，<br/>改換陰陽移禍福，<br/>勸君莫作等閒看。',
                'summary' => null,
                'level' => '中平',
                'code' => '辛癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'fortune_category_id' => 1,
                'fortune_no' => 81,
                'title' => '第八一籤',
                'content' => '假君財物自當還，<br/>謀賴欺心他自奸，<br/>幸有高臺明月鏡，<br/>請來對照破機關。',
                'summary' => '(欺心二字，另有改作心欺一說)',
                'level' => '中平(中吉)',
                'code' => '壬甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'fortune_category_id' => 1,
                'fortune_no' => 82,
                'title' => '第八二籤',
                'content' => '彼亦儔中一輩賢，<br/>勸君特達與周旋，<br/>此時賓主歡相會，<br/>他日王侯卻並肩。',
                'summary' => null,
                'level' => '上吉',
                'code' => '壬乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'fortune_category_id' => 1,
                'fortune_no' => 83,
                'title' => '第八三籤',
                'content' => '隨分堂前赴粥饘，<br/>何須妄想苦憂煎，<br/>主張門戶誠難事，<br/>百歲安閒得幾年。',
                'summary' => null,
                'level' => '下下',
                'code' => '壬丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'fortune_category_id' => 1,
                'fortune_no' => 84,
                'title' => '第八四籤',
                'content' => '君家事緒更紛然，<br/>當局須知一著先，<br/>長舌婦人休酷聽，<br/>力行禮義要心堅。',
                'summary' => '(君家二字，另有改作箇中一說)',
                'level' => '中平',
                'code' => '壬丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'fortune_category_id' => 1,
                'fortune_no' => 85,
                'title' => '第八五籤',
                'content' => '一春風雨正瀟瀟，<br/>千里行人去路遙，<br/>移寡就多君得計，<br/>如何歸路轉無聊。',
                'summary' => null,
                'level' => '中平',
                'code' => '壬戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'fortune_category_id' => 1,
                'fortune_no' => 86,
                'title' => '第八六籤',
                'content' => '一舟行貨好招邀，<br/>積少成多自富饒，<br/>常把他人比自己，<br/>管須日後勝今朝。',
                'summary' => '(舟字，另有作般字一說)',
                'level' => '上上(上吉)',
                'code' => '壬己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'fortune_category_id' => 1,
                'fortune_no' => 87,
                'title' => '第八七籤',
                'content' => '陰裏詳看怪爾曹，<br/>舟中敵國笑中刀，<br/>藩籬剖破渾無事，<br/>一種天生惜鳳毛。',
                'summary' => '(國字，另有改作圖字一說)<br/>(鳳字，另有改作羽字一說)',
                'level' => '下下',
                'code' => '壬庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'fortune_category_id' => 1,
                'fortune_no' => 88,
                'title' => '第八八籤',
                'content' => '從前作事總徒勞，<br/>纔見新春時漸遭，<br/>百計營求都得意，<br/>更須守己莫心高。',
                'summary' => '(時漸二字，另有改作喜氣一說)',
                'level' => '上吉',
                'code' => '壬辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'fortune_category_id' => 1,
                'fortune_no' => 89,
                'title' => '第八九籤',
                'content' => '樽前無事且高歌，<br/>時未來兮奈若何，<br/>白馬渡江雖日暮，<br/>虎頭城裏看巍峨。',
                'summary' => '(來兮，另有改作來時一說)<br/>(雖字，另有改作嘶字一說)',
                'level' => '中平',
                'code' => '壬壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'fortune_category_id' => 1,
                'fortune_no' => 90,
                'title' => '第九十籤',
                'content' => '崆峒城裏事如麻，<br/>無事如君有幾家，<br/>勸汝不須勤致禱，<br/>徒營生事苦咨嗟。',
                'summary' => '(營字，另有改作勞字一說)<br/>(嗟字，另有改作嘆字一說)',
                'level' => '中平',
                'code' => '壬癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'fortune_category_id' => 1,
                'fortune_no' => 91,
                'title' => '第九一籤',
                'content' => '佛說淘沙始見金，<br/>只緣君子苦勞心，<br/>榮華總得詩書效，<br/>妙裏工夫仔細尋。',
                'summary' => '(苦字，另有改作不字一說)',
                'level' => '中平(中吉)',
                'code' => '癸甲',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'fortune_category_id' => 1,
                'fortune_no' => 92,
                'title' => '第九二籤',
                'content' => '今年禾穀不如前，<br/>物價喧騰倍百年，<br/>災數流行多疫癘，<br/>一陽復後始安全。',
                'summary' => null,
                'level' => '下下(下中)',
                'code' => '癸乙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'fortune_category_id' => 1,
                'fortune_no' => 93,
                'title' => '第九三籤',
                'content' => '春來雨水太連綿，<br/>入夏晴乾雨又愆，<br/>節氣直交三伏始，<br/>喜逢滂沛足田園。',
                'summary' => '(太字，另有作大字一說)',
                'level' => '中平',
                'code' => '癸丙',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'fortune_category_id' => 1,
                'fortune_no' => 94,
                'title' => '第九四籤',
                'content' => '一般器用與人同，<br/>巧斲輪輿梓匠工，<br/>凡事有緣且隨分，<br/>秋冬方遇主人翁。',
                'summary' => '(斲指砍削)',
                'level' => '中平(中吉)',
                'code' => '癸丁',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'fortune_category_id' => 1,
                'fortune_no' => 95,
                'title' => '第九五籤',
                'content' => '知君袖裏有驪珠，<br/>生不逢辰亦強圖，<br/>可歎頭顱已如許，<br/>而今方得貴人扶。',
                'summary' => '(裏字，另有改作內字一說)<br/>(許通滸指岸邊。或許之左旁乃日之筆誤。大五碼無此字)<br/>(左日右午。指中午之太陽。借喻白首。)<br/>(左日右午。通晤。明也白也。 )',
                'level' => '中平(中吉)',
                'code' => '癸戊',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'fortune_category_id' => 1,
                'fortune_no' => 96,
                'title' => '第九六籤',
                'content' => '婚姻子媳莫嫌遲，<br/>但把精神仗佛持，<br/>四十年前須報應，<br/>功圓行滿有馨兒。',
                'summary' => ' (媳字有改作息字一說)<br/>(有字有改作育字一說)',
                'level' => '上吉',
                'code' => '癸己',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'fortune_category_id' => 1,
                'fortune_no' => 97,
                'title' => '第九七籤',
                'content' => '五十功名心已灰，<br/>那知富貴逼人來，<br/>更行好事存方寸，<br/>壽比岡陵位鼎台。',
                'summary' => null,
                'level' => '上上',
                'code' => '癸庚',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'fortune_category_id' => 1,
                'fortune_no' => 98,
                'title' => '第九八籤',
                'content' => '經營百出費精神，<br/>南北奔馳運未新，<br/>玉兔交時當得意，<br/>恰如枯木再逢春。',
                'summary' => null,
                'level' => '中平(中吉)',
                'code' => '癸辛',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'fortune_category_id' => 1,
                'fortune_no' => 99,
                'title' => '第九九籤',
                'content' => '貴人遭遇水雲鄉，<br/>冷淡交情滋味長，<br/>黃閣開時延故客，<br/>驊騮應得驟康莊。',
                'summary' => '(黃閣。指丞相公廨。漢公孫宏有開閣延賓故事)',
                'level' => '上上',
                'code' => '癸壬',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'fortune_category_id' => 1,
                'fortune_no' => 100,
                'title' => '第一百籤',
                'content' => '我本天仙雷雨師，<br/>吉凶禍福我先知，<br/>至誠禱告皆靈驗，<br/>抽得終籤百事宜。',
                'summary' => '(告字另有改祝字一說)<br/>(驗字另有改應字一說)',
                'level' => '上上',
                'code' => '癸癸',
                'image' => null,
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
