<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\Fortune;

class Fortune05Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fortune::factory(150)->create();

        // 觀音二四籤
        Fortune::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 501,
                'sign_system_id' => 5,
                'number' => 1,
                'title' => '第一籤',
                'content' => '寶馬盈門吉慶多，<br/>官司有理勸調和，<br/>萬般得利稱全福，<br/>一箭紅心定中科。',
                'level' => '上吉',
                'code' => null,
                'image' => null,
                'memo' => '善才參世尊',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 502,
                'sign_system_id' => 5,
                'number' => 2,
                'title' => '第二籤',
                'content' => '彼此分明事不通，<br/>相爭善惡不相同，<br/>利名患病皆難吉，<br/>何必勞心問始終。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '賀海被災星',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 503,
                'sign_system_id' => 5,
                'number' => 3,
                'title' => '第三籤',
                'content' => '瑞氣騰騰最吉祥，<br/>行人有利即還鄉，<br/>若占官事和為貴，<br/>和合婚姻孕產璋。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '梁山伯訪友',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 504,
                'sign_system_id' => 5,
                'number' => 4,
                'title' => '第四籤',
                'content' => '在家富貴足安然，<br/>出外如同透碧天，<br/>秀士名登龍虎榜，<br/>農夫得遇大豐年。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '唐三藏取經',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 505,
                'sign_system_id' => 5,
                'number' => 5,
                'title' => '第五籤',
                'content' => '求名問利一時難，<br/>出外行人遇友蘭，<br/>萬事誠求神佛佑，<br/>管教即日保平安。',
                'level' => '中平',
                'code' => null,
                'image' => null,
                'memo' => '伍子胥逃關',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 506,
                'sign_system_id' => 5,
                'number' => 6,
                'title' => '第六籤',
                'content' => '一切謀為立便成，<br/>諸凡正直吉祥迎，<br/>婚姻名利皆如意，<br/>公事行人保泰盈。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '王氏女敬佛',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 507,
                'sign_system_id' => 5,
                'number' => 7,
                'title' => '第七籤',
                'content' => '求事謀婚總成空，<br/>官災口舌藥無功，<br/>尋人失物難求覓，<br/>病阻行人路不通。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '玄武帝遭難',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 508,
                'sign_system_id' => 5,
                'number' => 8,
                'title' => '第八籤',
                'content' => '生平苦難更勞辛，<br/>且喜今年交運新，<br/>出遇貴人提拔處，<br/>猶如枯木再逢春。',
                'level' => '上中',
                'code' => null,
                'image' => null,
                'memo' => '劉智遠鬥瓜精',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 509,
                'sign_system_id' => 5,
                'number' => 9,
                'title' => '第九籤',
                'content' => '病人無事保安康，<br/>作事求財處處良，<br/>訟事安平行客至，<br/>夫妻和合百年長。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '何仙姑訪道',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 510,
                'sign_system_id' => 5,
                'number' => 10,
                'title' => '第十籤',
                'content' => '鴛鴦分散各無心，<br/>口舌官司禍患深，<br/>病者防亡有外鬼，<br/>行人托友去無音。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '孟姜女尋夫',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 511,
                'sign_system_id' => 5,
                'number' => 11,
                'title' => '十一籤',
                'content' => '門庭吉慶福無邊，<br/>相接高人事可全，<br/>名利兩般多有望，<br/>更能修善子孫賢。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '劉文龍上任',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 512,
                'sign_system_id' => 5,
                'number' => 12,
                'title' => '十二籤',
                'content' => '鮮花逢雨又遭霜，<br/>月被雲遮雪見揚，<br/>凡事不如守舊好，<br/>貪斜只恐有驚傷。',
                'level' => '下中',
                'code' => null,
                'image' => null,
                'memo' => '鳳仙女招親',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 513,
                'sign_system_id' => 5,
                'number' => 13,
                'title' => '十三籤',
                'content' => '萬事諸般莫自迷，<br/>官司病患不多期，<br/>孕男婚合家中吉，<br/>失物行人明後時。',
                'level' => '中平',
                'code' => null,
                'image' => null,
                'memo' => '劉先主入贅',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 514,
                'sign_system_id' => 5,
                'number' => 14,
                'title' => '十四籤',
                'content' => '婚姻和合病離床，<br/>謀事求財主吉昌，<br/>失物遷移皆遂意，<br/>官司有理定無妨。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '花子隱如意',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 515,
                'sign_system_id' => 5,
                'number' => 15,
                'title' => '十五籤',
                'content' => '行人立志順風船，<br/>爭訟年豐卻勝前，<br/>若是求謀多稱意，<br/>貴人接引友周全。',
                'level' => '上中',
                'code' => null,
                'image' => null,
                'memo' => '朱買臣求官',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 516,
                'sign_system_id' => 5,
                'number' => 16,
                'title' => '十六籤',
                'content' => '求財主有貴人招，<br/>病者無妨心莫焦，<br/>凡事須從勤修省，<br/>行人定至待明朝。',
                'level' => '上吉',
                'code' => null,
                'image' => null,
                'memo' => '舜天子傳位',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 517,
                'sign_system_id' => 5,
                'number' => 17,
                'title' => '十七籤',
                'content' => '官司橫事受諸災，<br/>家內人丁大破財，<br/>凡病必須先了願，<br/>管教脫悔笑顏開。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '林招德放黃鶯',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 518,
                'sign_system_id' => 5,
                'number' => 18,
                'title' => '十八籤',
                'content' => '出門見鬼遇兇人，<br/>買賣經營徒苦辛，<br/>名利兩般都不順，<br/>勸君守舊待來春。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '楊文廣傷身',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 519,
                'sign_system_id' => 5,
                'number' => 19,
                'title' => '十九籤',
                'content' => '官司何必決雌雄，<br/>病者誠心求上穹，<br/>起造姻緣田地吉，<br/>出門生意四時通。',
                'level' => '上中',
                'code' => null,
                'image' => null,
                'memo' => '漢光武鬧昆陽',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 520,
                'sign_system_id' => 5,
                'number' => 20,
                'title' => '二十籤',
                'content' => '婚姻名利問如何，<br/>石上栽松根必無，<br/>病者不安官有累，<br/>誠求佛力暗中扶。',
                'level' => '下中',
                'code' => null,
                'image' => null,
                'memo' => '韓信築壇拜將',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 521,
                'sign_system_id' => 5,
                'number' => 21,
                'title' => '二一籤',
                'content' => '家門喜慶得功名，<br/>道業興隆謀亦成，<br/>一切求財名得意，<br/>喜星高照吉星迎。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '濮十藝投親',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 522,
                'sign_system_id' => 5,
                'number' => 22,
                'title' => '二二籤',
                'content' => '出入行舟多笑容，<br/>家中財寶喜重重，<br/>官司有理行人至，<br/>病者雖危不見凶。',
                'level' => '上上',
                'code' => null,
                'image' => null,
                'memo' => '海龍女比武',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 523,
                'sign_system_id' => 5,
                'number' => 23,
                'title' => '二三籤',
                'content' => '名利求謀事不祥，<br/>病有鬼祟不離床，<br/>全憑作福求天佛，<br/>門內神明燒一香。',
                'level' => '下下',
                'code' => null,
                'image' => null,
                'memo' => '蔡伯喈辭朝',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 524,
                'sign_system_id' => 5,
                'number' => 24,
                'title' => '二四籤',
                'content' => '謀望婚姻俱得圓，<br/>病人即日可安痊，<br/>名成利就行無阻，<br/>水面經營常順船。',
                'level' => '上吉',
                'code' => null,
                'image' => null,
                'memo' => '文王遇子牙',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
