<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// Models
use App\Models\Fortune;

class Fortune09Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fortune::factory(150)->create();

        // 註生娘娘三十籤
        Fortune::upsert(
            $this->datas(),
            ['id']
        );
    }

    private function datas(): array
    {
        $now = now();
        return [
            [
                'id' => 901,
                'fortune_category_id' => 9,
                'fortune_no' => 1,
                'title' => '第一籤',
                'content' => '好事從來有，<br/>須當仔細尋，<br/>千般無阻滯，<br/>不用前進心。',
                'summary' => '求財平<br/>婚姻平<br/>行人緩<br/>貴人緩<br/>失物緩可獲<br/>經營要仔細<br/>田厝不吉<br/>出外不吉<br/>舊居無妨<br/>運途平常<br/>病難急癒<br/>訴訟不利<br/>風水再尋守舊無碍<br/>此籤列第一首，凡事要貴人，謹慎不可輕易，神意叮嚀斟酌不可不守也。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/01.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 902,
                'fortune_category_id' => 9,
                'fortune_no' => 2,
                'title' => '第二籤',
                'content' => '久雨漸初晴，<br/>雲開見日新，<br/>經求逢大利，<br/>爭訟得光亨。',
                'summary' => '謀財吉<br/>厝宅吉<br/>問醫吉<br/>婚姻吉<br/>田園吉<br/>貴人現<br/>官事吉<br/>久病吉<br/>失物東方尋，運途漸次通。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/02.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 903,
                'fortune_category_id' => 9,
                'fortune_no' => 3,
                'title' => '第三籤',
                'content' => '無事生煩惱，<br/>無災恐怕侵，<br/>相逢無利益，<br/>不用進前心。',
                'summary' => '求財無<br/>官事凶<br/>病多端<br/>貴人暗<br/>婚姻不成<br/>田厝不吉<br/>厝宅不吉<br/>問醫不合<br/>失物難尋<br/>運途未通<br/>凡事多疑，不如守坐。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/03.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 904,
                'fortune_category_id' => 9,
                'fortune_no' => 4,
                'title' => '第四籤',
                'content' => '明月出雲端，<br/>謀望有幾般，<br/>寬心行正道，<br/>不用仔細觀。',
                'summary' => '婚姻平平<br/>經營穩當<br/>求財平常<br/>厝宅平<br/>田園平<br/>醫師平<br/>貴人有<br/>失物月明可覓，月暗難尋。<br/>謀事正途平穩，偏途不利。<br/>訴訟受冤可解，奸詐則敗。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/04.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 905,
                'fortune_category_id' => 9,
                'fortune_no' => 5,
                'title' => '第五籤',
                'content' => '問病定無憂，<br/>爭訟有官箴（ㄓㄣ），<br/>萬古澄淡月，<br/>昨夜客回首。',
                'summary' => '病可癒<br/>婚姻成<br/>貴人來<br/>醫藥吉<br/>行人至<br/>田園吉<br/>訟可勝<br/>厝宅吉<br/>經營利小，淡淡而已。<br/>凡事逢月，則有佳音。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/05.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 906,
                'fortune_category_id' => 9,
                'fortune_no' => 6,
                'title' => '第六籤',
                'content' => '行行重行行，<br/>與君試一程，<br/>朱衣亦暗點，<br/>富貴得高名。',
                'summary' => '田園吉<br/>問醫吉<br/>厝宅吉<br/>求名有<br/>出外吉<br/>尋物緩<br/>求財有<br/>訴訟吉<br/>行人遲至<br/>貴人暗助，運途可通。<br/>試驗及第，凡事成功可望也。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/06.jpg',
                'memo' => '朱衣，五文昌帝君中之朱衣神君，參考故事如下：

朱衣暗點頭（朱衣，五文昌帝君中之朱衣神君）

　　蘇東坡二十二歲那年，去參加禮部考試。當時的主考官是歐陽修，他有兩句詩：「書有未曾經我讀，事無不可對人言。」

　　「書有未曾經我讀」，還比較謙虛，世界上的書有些大概我還沒讀過，這表示很謙虛，但又多傲慢！「事無不可對人言」，歐陽修的修養，生平沒有做對不起人的事，任何事都敢講。蘇東坡年輕時，曾聽歐陽修寫這兩句詩。後來他去考試，剛好歐陽修當主考官。你看他怎樣來整歐陽修？當時，歐陽修出了一個題目「刑賞忠厚之至論」。考試及第後，將來是做官，做官則要儘量寬厚，不可隨便判刑。蘇東坡在文章中就引用個典故：「堯的時候，一個人犯了罪，將要被殺，堯的司法官，臬陶曰：「殺之！」向上面報告了三次，都判他死罪。堯日：「宥之。」堯是皇帝，也將他駁下來三次。 

據說，歐陽修看考卷時，非常迷信，因為考卷都密封，不曉得是誰寫的文章，好與壞很難斷定。古時候，是用蠟燭光，在夜裏，濕氣又重，陰陰森森，鬼影幢幢，始終看到一位穿紅袍子的，站在他前面。有時，看到一篇好文章，正想要錄取，但抬頭見到那位紅袍的影子就不敢了，因為此人一定做了壞事，如果看完一篇文章後，再看到那位穿紅袍的點頭示意，那他就錄取了。所以，他有兩句詩：

文章千古無憑據，但願朱衣暗點頭。 

歐陽修一輩子不信這些，可是這回還是信了。文章那個好？那個壞？千古以來沒有憑據，只希望前面那位穿紅袍的神仙暗中點頭，但願不會錄取錯人。 

因為以前考功名，不但考學問，在道德上更重要，這是歐陽修當時的觀念。蘇東坡的文章，大概朱衣是暗點頭。但是這個典故出自何處？這個年輕人真了不起，我沒讀過的書，他竟然知道，非錄取他不可！錄取後學生當然要拜見老師。歐陽修吩咐門下說；「有個蘇軾的新榜生求見時，立刻通報」。先一套公式化的應酬、寒喧完後，歐陽修即問起考試時所引用的典故，出自何書？蘇東坡站起來回答：「老師，我想當然爾！」我想大概是那個樣子，書上根本就沒這個記載！此時，歐陽修有如啞巴吃了記悶棍，不過心裏真欣賞這個年輕人的氣派！雖給撞上了，但只是一笑置之！

資料來源：http://book.bfnn.org/books2/1360.htm',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 907,
                'fortune_category_id' => 9,
                'fortune_no' => 7,
                'title' => '第七籤',
                'content' => '嶺上一支梅，<br/>幾處經霜雪，<br/>唯有暗飄香，<br/>清秀如皎月。',
                'summary' => '求財難<br/>病多端<br/>尋物難<br/>行人緩<br/>田園不利<br/>運途未通<br/>出外不利<br/>厝宅不利<br/>官事宜暗中運動，凡事正途難成功，偏途可僥倖得意也。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/07.jpg',
                'memo' => '所謂暗中運動，就是循非正常管道的意思。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 908,
                'fortune_category_id' => 9,
                'fortune_no' => 8,
                'title' => '第八籤',
                'content' => '紅火滿天炎，<br/>干戈日日新，<br/>若逢龍虎動，<br/>過了見太平。',
                'summary' => '求財無<br/>運途乖<br/>田園凶<br/>貴人暗<br/>厝宅凶<br/>婚不成<br/>訴訟凶<br/>醫不合<br/>凡事須過辰日或寅日，方有一線光明之福，但久病或大事則需過辰年或寅年庶無危險也，不然亦得辰寅月也。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/08.jpg',
                'memo' => '十二生肖對應十二天干，龍為辰，虎為寅。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 909,
                'fortune_category_id' => 9,
                'fortune_no' => 9,
                'title' => '第九籤',
                'content' => '一行雁虛空，<br/>貴人節節逢，<br/>庭前枯樹發，<br/>祿馬又添粧。',
                'summary' => '久病吉<br/>貴人現<br/>醫藥無效<br/>經營成功<br/>訴訟可勝<br/>田厝先凶後吉<br/>求財先難後易<br/>凡事逢春更好。<br/>婚事重姻最合。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/09.jpg',
                'memo' => '祿馬是古代狀元所騎的馬。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 910,
                'fortune_category_id' => 9,
                'fortune_no' => 10,
                'title' => '第十籤',
                'content' => '日出高逢上，<br/>便照四方明，<br/>凶星盡迴避，<br/>散處可堪行。',
                'summary' => '行人至<br/>病可癒<br/>田園吉<br/>出外吉<br/>厝宅吉<br/>求財平<br/>貴人現<br/>婚姻平<br/>運途否極泰來，凡事逢凶化吉。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/10.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 911,
                'fortune_category_id' => 9,
                'fortune_no' => 11,
                'title' => '第十一籤',
                'content' => '花發春前旺，<br/>秋風似不宜，<br/>看來日下事，<br/>是非莫管他。',
                'summary' => '婚姻兇<br/>訴訟凶<br/>厝宅凶<br/>田園凶<br/>病多端<br/>醫不合<br/>下種凶<br/>出外凶<br/>貴人暗<br/>運途乖<br/>穀失敗<br/>求財無<br/>此籤在春天得之猶是平平，若是秋冬得之則更不佳。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/11.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 912,
                'fortune_category_id' => 9,
                'fortune_no' => 12,
                'title' => '第十二籤',
                'content' => '運數未亨通，<br/>惡星屢相逢，<br/>祈禳吉日至（禳ㄖㄤˊ），<br/>免得落空亡。',
                'summary' => '貴人暗<br/>訴訟凶<br/>婚姻凶<br/>田園凶<br/>求財無<br/>病禱神<br/>厝宅凶<br/>運未通<br/>出外凶<br/>醫不合<br/>凡事預防惡人相害，合謀生意必大不利。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/12.jpg',
                'memo' => '空亡的意思隨情況不同而異。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 913,
                'fortune_category_id' => 9,
                'fortune_no' => 13,
                'title' => '第十三籤',
                'content' => '宜積平生福，<br/>方應爵祿臨，<br/>生枝桃李樹，<br/>昨夜有喜音。',
                'summary' => '婚姻成<br/>病可癒<br/>財可求<br/>厝宅吉<br/>貴人來<br/>訟可勝<br/>運將通<br/>田園吉<br/>但凡事宜心存行善，不然則吉或能反凶也，又春天得之更佳。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/13.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 914,
                'fortune_category_id' => 9,
                'fortune_no' => 14,
                'title' => '第十四籤',
                'content' => '始初明月現，<br/>凡事盡皆通，<br/>遠行消息近，<br/>不久到深宮。',
                'summary' => '運將通<br/>貴人現<br/>厝宅吉<br/>婚姻成<br/>病可癒<br/>行人至<br/>田園吉<br/>訴訟苦<br/>求財多少<br/>尋物可獲<br/>此籤月明時得之則佳。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/14.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 915,
                'fortune_category_id' => 9,
                'fortune_no' => 15,
                'title' => '第十五籤',
                'content' => '在家財多有，<br/>出路宜破財，<br/>無人相勸保，<br/>定是官符來。',
                'summary' => '出外凶<br/>婚姻凶<br/>厝宅病<br/>田園平<br/>求財無<br/>運途乖<br/>病多端<br/>訴訟凶<br/>合夥不吉<br/>經營失意<br/>好事必敗<br/>省事最好',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/15.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 916,
                'fortune_category_id' => 9,
                'fortune_no' => 16,
                'title' => '第十六籤',
                'content' => '鐵船渡江海，<br/>一陣風浪來，<br/>若遇陰崖處，<br/>舉眼見三台。',
                'summary' => '出外凶<br/>求財難<br/>貴人緩<br/>田園凶<br/>婚姻難<br/>厝宅凶<br/>病多端<br/>運途乖<br/>失物難得<br/>孕婦生女<br/>牧畜不佳<br/>謀事多阻<br/>訴訟不利，最後若得貴人，或可消災解厄。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/16.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 917,
                'fortune_category_id' => 9,
                'fortune_no' => 17,
                'title' => '第十七籤',
                'content' => '兩年不豐登，<br/>今年見太平，<br/>久仇寃未改，<br/>禍去福重迎。',
                'summary' => '求財平<br/>貴人緩<br/>出外平<br/>行人至<br/>田園平<br/>穀豐收<br/>厝宅平<br/>孕生男<br/>尋物可獲<br/>此籤久年訴訟可得完結，<br/>若犯形事可服解放，<br/>婚姻先凶後吉續娶必好，<br/>凡是初作平平繼續便佳。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/17.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 918,
                'fortune_category_id' => 9,
                'fortune_no' => 18,
                'title' => '第十八籤',
                'content' => '貴人問前程，<br/>而今福祿生，<br/>若有官災至，<br/>緊守得安寧。',
                'summary' => '求財平<br/>孕生男<br/>田園平<br/>訟不可<br/>厝宅平<br/>行人至<br/>婚姻平<br/>勿出外<br/>貴人反覆，事恐中阻，<br/>暫時經營則好，久作則凶，<br/>凡事謹慎不可妄為。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/18.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 919,
                'fortune_category_id' => 9,
                'fortune_no' => 19,
                'title' => '第十九籤',
                'content' => '草木方暢茂，<br/>春風花草香，<br/>人生須快樂，<br/>福壽與天長。',
                'summary' => '運途吉<br/>婚姻吉<br/>耕作好<br/>下種吉<br/>孕生女<br/>求醫吉<br/>田園吉<br/>行人至<br/>厝宅吉<br/>訴訟苦<br/>貴人現<br/>求財有<br/>凡事無妄作皆好。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/19.jpg',
                'memo' => '所有籤詩都一樣，在不同境遇下會有不同籤解，求得此籤可求問神明是否有指示飲用花草茶之意。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 920,
                'fortune_category_id' => 9,
                'fortune_no' => 20,
                'title' => '第二十籤',
                'content' => '遇見太陽星，<br/>凡事得安寧，<br/>經求逢大吉，<br/>爭訟得咸亨。',
                'summary' => '財利多<br/>貴人現<br/>訴訟勝<br/>田厝吉<br/>孕生男<br/>行人至<br/>尋物現<br/>病可癒<br/>運途通<br/>婚姻吉<br/>試驗及第<br/>求雨反晴<br/>此籤面朝東方最佳，向西方就不利。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/20.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 921,
                'fortune_category_id' => 9,
                'fortune_no' => 21,
                'title' => '第二十一籤',
                'content' => '日斜樹影動，<br/>雨壓上苑花，<br/>雞鳴三五夜，<br/>祿馬水雲涯。',
                'summary' => '求財在水邊<br/>孕婦要生女<br/>凡事月明時<br/>方有貴人遇<br/>田厝平<br/>訟不吉<br/>婚姻凶<br/>貴人暗<br/>求雨可得<br/>耕種亦佳<br/>尋物水邊<br/>種花不吉',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/21.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 922,
                'fortune_category_id' => 9,
                'fortune_no' => 22,
                'title' => '第二十二籤',
                'content' => '漢外黑雲飛，<br/>雷霆霹靂推，<br/>人心皆似鐵，<br/>官法火爐開。',
                'summary' => '訟志凶<br/>婚不吉<br/>求財無<br/>病危險<br/>運顛倒<br/>用人凶<br/>田厝凶<br/>醫不合<br/>用人凶<br/>耕種不吉<br/>謀事不吉<br/>孕生男<br/>此籤訴訟民事恐變刑事，如果刑事更不吉。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/22.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 923,
                'fortune_category_id' => 9,
                'fortune_no' => 23,
                'title' => '第二十三籤',
                'content' => '聖帝行符勅（勅ㄔˇ），<br/>流名傳世間，<br/>凶星盡迴避，<br/>國泰與民安。',
                'summary' => '求財平<br/>求名有<br/>婚姻吉<br/>病可癒<br/>謀事好<br/>運途通<br/>訴訟吉<br/>貴人現<br/>行人未至<br/>田厝皆吉<br/>五谷豐登<br/>癘疫平靜（癘ㄌㄧˋ）<br/>孕婦月初生男，月渺生女。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/23.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 924,
                'fortune_category_id' => 9,
                'fortune_no' => 24,
                'title' => '第二十四籤',
                'content' => '見官終有理，<br/>占病定無憂，<br/>求財多得遂，<br/>凡事盡綢繆。',
                'summary' => '來訴訟吉<br/>謀事成<br/>出外吉<br/>求財吉<br/>病可癒<br/>運途通<br/>貴人現<br/>田厝吉<br/>百事亨嘉，不用憂慮<br/>孕婦前胎生男則生男，<br/>前胎生女則生女，<br/>初胎生男。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/24.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 925,
                'fortune_category_id' => 9,
                'fortune_no' => 25,
                'title' => '第二十五籤',
                'content' => '無翼豈自飛，<br/>無足豈自行，<br/>遠來皆不泰，<br/>恐怕向前程。',
                'summary' => '貴人暗<br/>訴訟凶<br/>求財難<br/>田厝吉<br/>求醫凶<br/>謀事危<br/>失物難尋<br/>行人未至<br/>孕婦生女恐難保全。<br/>百事須退不宜進。<br/>運途不吉老人病危，若逢久病恐有變。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/25.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 926,
                'fortune_category_id' => 9,
                'fortune_no' => 26,
                'title' => '第二十六籤',
                'content' => '畫燭當風炎，<br/>無風燭自搖，<br/>臨官不用早，<br/>花發落地空。',
                'summary' => '訴訟凶<br/>婚姻凶<br/>失物無<br/>花價敗<br/>田厝凶<br/>耕種凶<br/>生意恐內陷<br/>孕婦產不育<br/>老人病危<br/>運途艱難<br/>物價下跌<br/>行人未至<br/>出外凶多<br/>謀事不可',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/26.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 927,
                'fortune_category_id' => 9,
                'fortune_no' => 27,
                'title' => '第二十七籤',
                'content' => '凡事能見消，<br/>家門破憂災，<br/>遠行宜且止，<br/>福去頻禍來。',
                'summary' => '訴訟凶<br/>婚姻凶<br/>出外凶<br/>田園兇<br/>厝宅凶<br/>求財無<br/>失物難尋<br/>求醫不吉<br/>做事顛倒<br/>運途坎坷<br/>行人不至<br/>凶多吉少',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/27.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 928,
                'fortune_category_id' => 9,
                'fortune_no' => 28,
                'title' => '第二十八籤',
                'content' => '葵花謝又開，<br/>遠者去重來，<br/>任他險不險，<br/>任災不見災。',
                'summary' => '新婚凶<br/>田厝平<br/>貴人現<br/>重婚好<br/>行人至<br/>病不畏<br/>繼續則吉，初作不佳<br/>運途無碍<br/>訴訟始敗終勝。<br/>刑事先凶後吉。<br/>久病不能斷根。<br/>孕生女，初胎不育，次胎安全。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/28.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 929,
                'fortune_category_id' => 9,
                'fortune_no' => 29,
                'title' => '第二十九籤',
                'content' => '崑崙高峰上，<br/>遇見呂仙翁，<br/>賜伊財寶物，<br/>凡事得禎祥。',
                'summary' => '貴人現<br/>孕生男<br/>經營吉<br/>訟必勝<br/>求財吉<br/>行人至<br/>外出吉<br/>修墓吉<br/>婚姻吉<br/>田厝吉<br/>運亨通<br/>求醫吉',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/29.jpg',
                'memo' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 930,
                'fortune_category_id' => 9,
                'fortune_no' => 30,
                'title' => '第三十籤',
                'content' => '參拾增一枝（三十添一支），<br/>未來我先知，<br/>萬事皆合意，<br/>添油正合宜（添油皆合宜 ）。',
                'summary' => '訴訟吉<br/>謀事成<br/>行人緩<br/>出外吉<br/>貴人遲<br/>求財有<br/>田厝吉<br/>婚姻吉<br/>耕種吉<br/>孕生男<br/>凡得此籤宜于神前添油，獲福無疆。',
                'level' => null,
                'code' => null,
                'image' => '/images/fortunes/09/30.jpg',
                'memo' => '本籤類似雷雨師一百籤之第一百籤，籤詩中提及增一支，是否鑑於本籤僅有祝福未提細節，需再求一支籤詩請神明指點細節，可以再請示確認。',
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
